# Generated by Django 3.2.4 on 2023-08-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0006_alter_userprofile_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pdf_file',
        ),
    ]
