# Generated by Django 3.2.4 on 2023-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0009_auto_20230810_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, default='', null=True, upload_to='resumes/'),
        ),
    ]
