# Generated by Django 3.2.4 on 2023-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0028_auto_20230812_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skillstxt',
            field=models.CharField(default='', max_length=10485750),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='match',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pho1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pho2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
