# Generated by Django 3.2.4 on 2023-08-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_auto_20230813_0627'),
        ('seeker', '0029_auto_20230812_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hrreview',
            field=models.CharField(default='', max_length=104750),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interviewscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='job_applicants', to='recruiter.Jobs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
