# Generated by Django 3.2.4 on 2023-08-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0030_auto_20230813_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questin', models.CharField(default='', max_length=10485750)),
                ('Answer', models.CharField(default='', max_length=10485750)),
                ('Evalution', models.CharField(default='', max_length=100)),
                ('forjobs', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interviewres',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='applied_interview',
            field=models.ManyToManyField(blank=True, related_name='applied_interview', to='seeker.InterviewQ'),
        ),
    ]
