# Generated by Django 3.2.4 on 2023-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('exp', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('Intern', 'Intern'), ('Cleark', 'Cleark')], max_length=13)),
                ('gen', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=6)),
                ('ad1', models.CharField(max_length=100)),
                ('ad2', models.CharField(max_length=100)),
                ('pho1', models.CharField(max_length=100)),
                ('pho2', models.CharField(max_length=100)),
                ('work', models.CharField(choices=[('Open to Work', 'Open to Work'), ('Viewer', 'Viewer')], max_length=13)),
                ('edu', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('exp', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('Intern', 'Intern'), ('Cleark', 'Cleark')], max_length=13)),
                ('gen', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=6)),
                ('ad1', models.CharField(max_length=100)),
                ('ad2', models.CharField(max_length=100)),
                ('pho1', models.CharField(max_length=100)),
                ('pho2', models.CharField(max_length=100)),
                ('work', models.CharField(choices=[('Open to Work', 'Open to Work'), ('Viewer', 'Viewer')], max_length=13)),
                ('edu', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
    ]
