# Generated by Django 3.2.4 on 2023-08-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_delete_application'),
        ('seeker', '0003_auto_20230808_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, default=None, to='recruiter.Jobs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passw',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
