# Generated by Django 3.2.4 on 2023-08-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0008_userprofile_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
