# Generated by Django 3.2.4 on 2023-08-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0025_auto_20230811_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resumetxt',
            field=models.CharField(default='', max_length=10485750),
        ),
    ]
