# Generated by Django 3.2.4 on 2023-08-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0026_alter_userprofile_resumetxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
