# Generated by Django 3.2.4 on 2023-08-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0027_alter_userprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='match',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ranking',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
