# Generated by Django 3.2.4 on 2023-08-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
