# Generated by Django 3.2.4 on 2023-08-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0029_auto_20230812_1448'),
        ('recruiter', '0009_jobs_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='intervieweda',
            field=models.ManyToManyField(blank=True, related_name='interviewed_as_applicant', to='seeker.UserProfile'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='interviewednts',
            field=models.ManyToManyField(blank=True, related_name='interviewed_jobs', to='seeker.UserProfile'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='shortlistedappl',
            field=models.ManyToManyField(blank=True, related_name='shortlisted_jobs', to='seeker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='job_applications', to='seeker.UserProfile'),
        ),
    ]
