# Generated by Django 3.2.4 on 2023-08-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_auto_20230813_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
