# Generated by Django 3.2.4 on 2023-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=100)),
                ('dobs', models.DateField()),
                ('dobe', models.DateField()),
                ('exp', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('p', 'Part Time'), ('f', 'Full Time'), ('i', 'Internship')], default='default_typ', max_length=16)),
                ('sector', models.CharField(max_length=100)),
                ('openings', models.CharField(max_length=100)),
                ('creteria1', models.CharField(max_length=100)),
                ('creteria2', models.CharField(max_length=100)),
                ('creteria3', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
    ]
