# Generated by Django 3.2.4 on 2023-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_rename_job_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
