# Generated by Django 3.2.4 on 2023-08-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
