# Generated by Django 3.2.4 on 2023-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_auto_20230808_2316'),
        ('recruiter', '0008_jobs_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applicants',
            field=models.ManyToManyField(blank=True, to='seeker.UserProfile'),
        ),
    ]
